version: '3.8'

services:
  app:
    container_name: nestjs_boilerplate
    image: node:19
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mysql_data:


networks:
  backend:
