export enum EventConfigs {
  UPDATE_YAHOO_STOCK = 'UPDATE_YAHOO_STOCK',
  SCRAPE_ALL_STOCKS = 'SCRAPE_ALL_STOCKS',
  SCRAPE_ALL_STOCKS_RESPONSE = 'SCRAPE_ALL_STOCKS_RESPONSE',
  SCRAPE_ALL_STOCKS_DETAILS = 'SCRAPE_ALL_STOCKS_DETAILS',
  SCRAPE_ALL_STOCKS_DETAILS_RESPONSE = 'SCRAPE_ALL_STOCKS_DETAILS_RESPONSE',
}
